app:
  mode: "local"

storage:
  host: "postgres"
  user: "postgres"
  password: "rootroot"
  port: 5432
  database: "BankApp"
  migration: true

message_broker:
  consumer:
    brokers:
      - "kafka:9092"
    group_id: ""
    commit_interval: 1s
  consumer_topics:
    client_created_event: "client-created-event"
    account_created_event: "account-created-event"
    transaction_created_event: "transaction-created-event"

  producer:
    brokers:
      - "kafka:9092"
    batch_size: 10
    batch_timeout: 500ms
  producer_topics:
    account_balance_update: "account_balance_update"
