version: "3.8"

services:
  bank-commands:
    build:
      context: ./bank-commands
      dockerfile: Dockerfile
    ports:
      - "44044:44044"
    volumes:
      - ./bank-commands/configs/app/local.yaml:/app/configs/app/local.yaml
    environment:
      CONFIG_PATH: "/app/configs/app/local.yaml"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: BankApp
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
