app:
  mode: "local"

storage:
  host: "localhost"
  user: "postgres"
  password: "rootroot"
  port: 5433
  database: "BankApp"
  migration: true

grpc:
  port: 44044
  timeout: 5s
  time: 15min
  max_connection_idle: 5min
  max_connection_age: 5min
