up-migrations:
	goose postgres "postgres://postgres:rootroot@localhost:5435/BankApp?sslmode=disable" up

down-migrations:
	goose postgres "postgres://postgres:rootroot@localhost:5435/BankApp?sslmode=disable" down
