app:
  mode: "local"
  outbox_batch_size: 5
  ticker: 15s

storage:
  host: "postgres"
  user: "postgres"
  password: "rootroot"
  port: 5432
  database: "BankApp"
  migration: true

kafka:
  topics:
    client_created_event: "client-created-event"
    account_created_event: "account-created-event"
    transaction_created_event: "transaction-created-event"
  brokers:
    - "kafka:9092"